### ISSUE TITLE
Entrant profile only shows my first waitlisted event

### ISSUE THREAD

**Issue by ellismcdougald** [CMPUT301F24dragon/lucky-dragons#79]
I am waitlisted for multiple events: "New Event" (id HgJVsnES5VXY37XQ3hvZ) and "Lottery Test Event" (bAjHjU30R0Vzwes4l5Zh). But I only see "New Event" on the entrant profile under waitlisted events.

**Comment by ahmedsiad** [comment]
This happens because for some reason, the ListView height only shows the first item, and you have to scroll on it to see the other events. I think online its because the fragment is inside a ScrollView, so the ListView is also inside a ScrollView which causes the issue. The organizer profile page list would also have the same problem, but our current workaround is to just hardcode the ListView's linear layout to be super tall. I think there should be a better way to fix this though (do we need that ScrollView?)
